# Generated by Django 5.0.2 on 2024-04-16 21:40

from django.db import migrations


def populate_data(apps, schema_editor):
    EnglishPhrase = apps.get_model('tutor', 'EnglishPhrase')
    ExampleSentence = apps.get_model('tutor', 'ExampleSentence')

    # Populate EnglishPhrase table
    phrases = [
        "must", "have to", "need to", "should", "ought to",
        "can", "could", "may", "might", "will", "would",
        "shall", "used to", "dare to", "need", "had better",
        "would rather", "supposed to", "meant to", "bound to",
        "liable to", "going to"
    ]
    for phrase in phrases:
        EnglishPhrase.objects.create(phrase=phrase)

    # Populate ExampleSentence table
    sentences = {
        "must": [
            "You must finish your homework before going out.",
            "She must attend the meeting tomorrow.",
            "We must arrive at the airport by 5 PM.",
            "They must follow the rules at the school.",
            "He must apologize for his mistake.",
            "You must wear a seatbelt while driving.",
            "She must study hard for the exam.",
            "We must pay the bill before leaving the restaurant.",
            "They must return the library books next week.",
            "He must complete the project by Friday.",
            "I must call my parents.",
            "You must watch this movie.",
            "She must visit her grandmother.",
            "We must clean the house.",
            "They must learn from their mistakes."
        ],
        "have to": [
            "I have to wake up early for work.",
            "You have to submit the assignment by tomorrow.",
            "She has to take care of her younger siblings.",
            "We have to attend the seminar next week.",
            "They have to clean their room every weekend.",
            "He has to call his parents regularly.",
            "You have to follow the instructions carefully.",
            "She has to prepare for the presentation.",
            "We have to book the tickets in advance.",
            "They have to pass the driving test.",
            "I have to finish the report.",
            "You have to read the book for the class.",
            "She has to complete the project.",
            "We have to solve the problem.",
            "They have to attend the meeting."
        ],
     
    }
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data),

    ]
